### ISSUE TITLE
Server may have something wrong

### ISSUE THREAD

**Issue by wzy461143268** [openmm/spice-dataset#95]
`python .\downloader.py
Processing SPICE Solvated Amino Acids Single Points Dataset v1.1
Processing SPICE Dipeptides Single Points Dataset v1.2
Traceback (most recent call last):
  File "D:\dataset\spice-dataset\downloader\downloader.py", line 111, in <module>
    recs = list(dataset.iterate_records(specification_names=specifications))
  File "C:\Users\wangzhongyao\scoop\apps\miniconda3\current\envs\openmm\lib\site-packages\qcportal\dataset_models.py", line 972, in iterate_records
    self._internal_fetch_records(batch_tofetch, [spec_name], status, include)
  File "C:\Users\wangzhongyao\scoop\apps\miniconda3\current\envs\openmm\lib\site-packages\qcportal\dataset_models.py", line 724, in _internal_fetch_records
    records = self._client._get_records_by_type(self._record_type, record_ids, include=include)
  File "C:\Users\wangzhongyao\scoop\apps\miniconda3\current\envs\openmm\lib\site-packages\qcportal\client.py", line 651, in _get_records_by_type
    record_data = self.make_request(
  File "C:\Users\wangzhongyao\scoop\apps\miniconda3\current\envs\openmm\lib\site-packages\qcportal\client_base.py", line 408, in make_request
    r = self._request(
  File "C:\Users\wangzhongyao\scoop\apps\miniconda3\current\envs\openmm\lib\site-packages\qcportal\client_base.py", line 373, in _request
    raise PortalRequestError(f"Request failed: {details['msg']}", r.status_code, details)
qcportal.client_base.PortalRequestError: Request failed: Bad Gateway (HTTP status 502)
`
Do you have some advice for me? Thanks!

**Comment by wzy461143268** [comment]
![image](https://github.com/openmm/spice-dataset/assets/47234030/eb06100a-422a-47b3-b6a4-7143ec5eca7e)

**Comment by peastman** [comment]
@bennybp it's the bad gateway error again.
